apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ducla-agent
  namespace: ducla-system
  labels:
    app: ducla-agent
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ducla-agent
