apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ducla-agent
  namespace: ducla-system
  labels:
    app: ducla-agent
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: ducla-agent
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
